[database]

username = 'mbentley'
address = 'localhost'
port = 22

[[hosts]]

# TODO: add documentation here for each element.

name = 'thinkpad-laptop'
port = 22
address = 'localhost'
flit_path = 'git/FLiT/scripts/flitcli/flit.py'
config_dir = 'git/FLiT/litmus-tests'

  [[hosts.compilers]]

  # TODO: figure out how to specify path for each host machine
  # TODO: what if the compilers list is part of the host?
  name = 'g++-5.4.0'
  binary = '/usr/bin/g++'
  type = 'gcc'
  optimization_levels = [
    '-O0',
    '-O1',
    '-O2',
    '-O3',
    #'-Ofast',
    #'-O...' ?
  ]
  switches = [
    '',
    '-fassociative-math',
    '-mavx',
    '-mp1',
    '-mavx2 -mfma',
    # ...
  ]
  

